Update documentations
Signed-off-by: Jaymin Suthar <sjaymin.us@gmail.com>

diff --git a/bin/acs_x86 b/bin/acs_x86
--- a/bin/acs_x86
+++ b/bin/acs_x86
@@ -1,4 +1,4 @@
 #!/system/bin/sh
 
-echo >&2 "I shouldn't be here, where did you get the zip?"
+echo >&2 "I should be a binary, build error?"
 exit 1
diff --git a/system/xbin/acs b/system/xbin/acs
--- a/system/xbin/acs
+++ b/system/xbin/acs
@@ -1,4 +1,4 @@
 #!/system/bin/sh
 
-echo >&2 "This is a placeholder script that will be replaced by acs binary."
+echo >&2 "I was supposed to be replaced by the installer, errors ?"
 exit 1
