Minor documentation update
Signed-off-by: Jaymin Suthar <sjaymin.us@gmail.com>

diff --git a/arm/xbin/acs b/arm/xbin/acs
--- a/arm/xbin/acs
+++ b/arm/xbin/acs
@@ -1,4 +1,8 @@
 #!/system/bin/sh
 
-echo >&2 "I should be a binary, build error?"
-exit 1
+abort() {
+	echo >&2 "ERROR: $1"
+	exit 1
+}
+
+abort "I should be a binary, build error?"
